/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function findMostSimilar(array: Array<string>, target: string): string
export function levenshteinDistance(a: string, b: string): string
